### ISSUE TITLE
Change build.yml action

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation-ui#14]
Triggered by a failed bundle build action, we found that the action is not useful in its current form anymore. It was used to publish the UI bundle to the nexus. We don't need that anymore, as the UI repo is now a submodule in the documentation repo, but we still would like to keep the linting, and checking that the bundle can be built on PRs.

This ticket is done when:
- [x] the build.yml action is ran on PRs as a required action - Here a PR with the action running sucessfully: https://github.com/stackabletech/documentation-ui/pull/19
- [x] the action does not contain the "Publish Bundle to Nexus" step anymore
- [x] the published bundle is removed in the nexus
- [ ] ~the nexus access token is removed from the repository~ (it's an org secret, can't be removed)
- [x] the action actually is green

**Comment by nightkr** [comment]
We should probably also reduce the scope a fair bit here. Linting is still valuable but should probably be moved to running for PRs instead. The push is useless since we now rebuild from stackabletech/documentation anyway.

**Comment by fhennig** [comment]
> The push is useless

What do you mean with push?

I looked at this and I noticed that `npm ci` also fails for me locally, but `npm i` upgrades the package lock and then `npm ci` works again, which could be done to fix the problem of the action.

I agree that taking a step back we could look at whether the action should be changed or removed entirely.

I _believe_ that having the package-lock.json in there is still necessary for the build, even if the build is happening in a different repository. I tried removing the file and it didn't work.

Do you know more? I'm not sure who set all of this up actually

**Comment by fhennig** [comment]
I did a bit of reading more and I agree to what you say. The build action should be removed and replaced with a PR triggered action that runs linting.

package-lock in here is not required for building anymore since that is in the documentation repo, but we still need it to run the linting.

I'll sketch something out on how to move forward
