### ISSUE TITLE
Tracking Cookie generates warning

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation-ui#21]
Since the tracking was introduced, the site generates a warning:

> Cookie “__hs_do_not_track” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by lfrancke** [comment]
@fhennig Can you estimate how large this issue is? S, M, L, XL?

**Comment by fhennig** [comment]
I have no idea, it's also not very urgent. The error also happens on the main site, not just the docs. I told Fabian about it and he will forward it to Berlin Bytes.

EDIT: Fabian told me that they will likely solve this at the end of the month. I'll assign myself to keep this in mind, we could also put this in "tracking" but i'll try to track it in my own notes

**Comment by lfrancke** [comment]
Thank you! In that case we're waiting for an external party so it's appropriate to put it in track.

**Comment by fhennig** [comment]
Update: The tracking cookie does not generate this warning anymore. There are a lot of other warning that get generated now though

**Comment by lfrancke** [comment]
Okay....that's also not great but at least this ticket can be closed then I guess.

**Comment by fhennig** [comment]
Actually, all those warnings are just on stackable.tech, not on the docs site.

And I forgot to make the changes in the docs, I just checked the main page. I've made the changes now, toether with Fabian: https://github.com/stackabletech/documentation-ui/pull/26

**Comment by fhennig** [comment]
it is now deployed live. 

Not a single warning anymore :tada:
