### ISSUE TITLE
Add a footer to the doc pages (with trademark notes)

### ISSUE THREAD

**Issue by razvan** [stackabletech/documentation-ui#23]
Add a footer to the docs pages. This could contain links to the GH repos, contributor's guide and so on.

Here is an example from the Kubernetes docs:
![image](https://user-images.githubusercontent.com/84674/194095293-54866098-66fd-484d-beee-06064bae15da.png)

Edit (Felix): The footer should also contain the trademark notes, like on our main page:

![Image](https://user-images.githubusercontent.com/5787489/206999178-6a92fe65-9c4f-437b-8a87-911918cbeebb.png)

## Acceptance criteria

- [ ] all the docs pages have the same footer as the main page

## Steps

- [ ] copy-paste the footer into this repo
- [ ] update the UI repo reference in the documentation and rebuild

**Comment by fhennig** [comment]
This needs to be done in the UI, I'm moving the ticket there

**Comment by fhennig** [comment]
There is a CSS conflict with seemingly already existing usages of the `fa` CSS class? I'll have to investigate again.

**Comment by fhennig** [comment]
fixed in #34
