### ISSUE TITLE
Pin the top level menu

### ISSUE THREAD

**Issue by razvan** [stackabletech/documentation-ui#24]
The top level menu should not be hidden when scrolling down. This forces the reader to scroll up  when navigating between concepts and operator docs which becomes tedious quickly.

![image](https://user-images.githubusercontent.com/84674/194095858-2057b594-6b6c-4c63-8bb3-625307a0f84f.png)

**Comment by fhennig** [comment]
@lfrancke and @soenkeliebau also think it should be pinned, so we'll do it.

**Comment by Techassi** [comment]
Yes, I also like a pinned nav bar!
